FROM node:alpine 

WORKDIR /usr/src/app

COPY package*.json /usr/src/app

RUN npm install
RUN apt-get update || : && apt-get install python -y
RUN pip install -r ./Med~~Ease-ML/requirements.txt

COPY . /usr/src/app

CMD npm start